
package com.fym.lta.ui;

import com.fym.lta.bao.BaoFactory;
import com.fym.lta.bao.BuildingBao;
import com.fym.lta.bao.LoginEngine;
import com.fym.lta.dto.BuildingDto;

import java.util.Date;
import java.util.List;

import javax.swing.JOptionPane;

/**
 *
 * @author karima
 */
public class BuildingScreeen extends javax.swing.JPanel {

    BuildingBao buildingBaoObject = new BaoFactory().createBuildingBao();
    boolean updateFlag = false;

    /** Creates new form Building */
    public BuildingScreeen() {
        initComponents();
        if (buildingBaoObject.listBuilding() != null)
            buildingTableReset(buildingBaoObject.listBuilding());
        insertPanel.setVisible(false);
        // screenID = 1
        // now one step we will create an object of ScreenBao to know the current permission
        String permissionType = new BaoFactory().createScreenBao().getCurrentPermission(1);
        Utilities.mandate(ubdateBuildingBTN, insertBuildingBTN, deleteBuildingBTN, 1, permissionType);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        buildingTable = new javax.swing.JTable();
        ubdateBuildingBTN = new javax.swing.JButton();
        deleteBuildingBTN = new javax.swing.JButton();
        BuildingEnteredCode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        insertBuildingBTN = new javax.swing.JButton();
        searchBuildingBTN = new javax.swing.JButton();
        insertPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        desc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Building", 0, 0, new java.awt.Font("Adobe Arabic", 1, 24))); // NOI18N

        buildingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Code", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        buildingTable.setRowHeight(20);
        jScrollPane1.setViewportView(buildingTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ubdateBuildingBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ubdateBuildingBTN.setText("Update");
        ubdateBuildingBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubdateBuildingBTNActionPerformed(evt);
            }
        });

        deleteBuildingBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteBuildingBTN.setLabel("Delete");
        deleteBuildingBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBuildingBTNMouseClicked(evt);
            }
        });

        BuildingEnteredCode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BuildingEnteredCode.setText(" ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Enter Building Code ");

        insertBuildingBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        insertBuildingBTN.setText("Insert  New Building");
        insertBuildingBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertBuildingBTNMouseClicked(evt);
            }
        });
        insertBuildingBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBuildingBTNActionPerformed(evt);
            }
        });

        searchBuildingBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchBuildingBTN.setText("Search");
        searchBuildingBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBuildingBTNMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Description");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Code");

        code.setText(" ");

        desc.setText(" ");
        desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Save");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout insertPanelLayout = new javax.swing.GroupLayout(insertPanel);
        insertPanel.setLayout(insertPanelLayout);
        insertPanelLayout.setHorizontalGroup(
            insertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, insertPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(insertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(insertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        insertPanelLayout.setVerticalGroup(
            insertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(insertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(insertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ubdateBuildingBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138)
                        .addComponent(deleteBuildingBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141)
                        .addComponent(insertBuildingBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BuildingEnteredCode, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(searchBuildingBTN)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(insertPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insertPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BuildingEnteredCode, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchBuildingBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ubdateBuildingBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(deleteBuildingBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(insertBuildingBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Building ");
    }//GEN-END:initComponents
    //Update Buttom
    private void ubdateBuildingBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubdateBuildingBTNActionPerformed
        code.setText(buildingTable.getValueAt(buildingTable.getSelectedRow(), 0).toString());
        insertPanel.setVisible(true);
        code.setEnabled(false);
        updateFlag = true;
    }//GEN-LAST:event_ubdateBuildingBTNActionPerformed

    private void deleteBuildingBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBuildingBTNMouseClicked
     
        String code = buildingTable.getValueAt(buildingTable.getSelectedRow(), 0).toString();
        BuildingDto selectedBuilding_Delete = new BuildingDto(); // this Building i want to delete
        selectedBuilding_Delete.setCode(code);

        if (buildingBaoObject.deleteBuilding(selectedBuilding_Delete)) {
            {
                JOptionPane.showMessageDialog(this, "deleted");
                buildingTableReset(buildingBaoObject.listBuilding());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Can not delete may be deleted using another user ");
        }

    }//GEN-LAST:event_deleteBuildingBTNMouseClicked

    private void insertBuildingBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertBuildingBTNMouseClicked
        insertPanel.setVisible(true);
        code.setEnabled(true);
        updateFlag = false;
    }//GEN-LAST:event_insertBuildingBTNMouseClicked

    private void searchBuildingBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBuildingBTNMouseClicked
        if (BuildingEnteredCode.getText() != null)
            if (buildingBaoObject.SearchBuilding(BuildingEnteredCode.getText()) != null)
                buildingTableReset(buildingBaoObject.SearchBuilding(BuildingEnteredCode.getText()));
            else
                JOptionPane.showMessageDialog(this, "not found");
        else {
            JOptionPane.showMessageDialog(this, "you should enter a building code");
            buildingTableReset(buildingBaoObject.listBuilding());
        }
      
    }//GEN-LAST:event_searchBuildingBTNMouseClicked

    private void insertBuildingBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBuildingBTNActionPerformed
       
      
        
    }//GEN-LAST:event_insertBuildingBTNActionPerformed

    private void descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        BuildingBao business = new BaoFactory().createBuildingBao();
        BuildingDto b = new BuildingDto();

        b.setCode(code.getText());
        b.setDescription(desc.getText());
        if (updateFlag) {
            b.setUPDATE_DATE(new Date(System.currentTimeMillis()));
            b.setUPDATED_BY(LoginEngine.currentUser);
        } else {
            b.setINSERTION_DATE(new Date(System.currentTimeMillis()));
            b.setINSERTED_BY(LoginEngine.currentUser);

            b.setUPDATE_DATE(new Date(System.currentTimeMillis()));
            b.setUPDATED_BY(LoginEngine.currentUser);
        }
        if (business.saveBuilding(b)) {
            JOptionPane.showMessageDialog(this, "Saved");
            buildingTableReset(business.listBuilding());
        } else
            JOptionPane.showMessageDialog(this, "Can't Save");
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BuildingEnteredCode;
    private javax.swing.JTable buildingTable;
    private javax.swing.JTextField code;
    private javax.swing.JButton deleteBuildingBTN;
    private javax.swing.JTextField desc;
    private javax.swing.JButton insertBuildingBTN;
    private javax.swing.JPanel insertPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchBuildingBTN;
    private javax.swing.JButton ubdateBuildingBTN;
    // End of variables declaration//GEN-END:variables





    public void buildingTableReset(List<BuildingDto> buildings) {

        Object[][] usersArr = new Object[buildings.size()][2];

        for (int i = 0; i < buildings.size(); i++) {
            usersArr[i][0] = buildings.get(i).getCode();
            usersArr[i][1] = buildings.get(i).getDescription();

        }
        buildingTable.setModel(new javax.swing.table.DefaultTableModel(usersArr, new String[] {
                                                                       "CODE", "DESCRIPTION" }));
    }


}
