
package com.fym.lta.ui;

import com.fym.lta.bao.BaoFactory;
import com.fym.lta.bao.CourseBao;
import com.fym.lta.bao.LoginEngine;
import com.fym.lta.dto.CourseDto;
import com.fym.lta.dto.DepartmentDto;
import com.fym.lta.dto.LocationTypeDto;

import java.util.Date;
import java.util.List;

import javax.swing.JOptionPane;

/**
 *
 * @author Mina
 */
public class CourseScreen extends javax.swing.JPanel
{

private CourseBao courseobjBao = new BaoFactory().createCourseBao();

    boolean updateFlag = false ;
    
    

    List<DepartmentDto> allDepartments = new BaoFactory().createDepartmentBao().listDepartment();
    
    // how to get location types in combo box 
    List<LocationTypeDto> allLocationType = new BaoFactory().createLocationTypeBao().listLocationType();


    
    /** Creates new form CourseSearch */
    public CourseScreen() 

{
        initComponents();
        if(allDepartments!=null)
        listComboDepartment(allDepartments);
        if (courseobjBao.listCourses()!= null)
            courseTableReset(courseobjBao.listCourses());
        if(allLocationType!=null)
            listComboLocation(allLocationType) ; 
        insertPanel.setVisible(false);
        int permissionType = new BaoFactory().createScreenBao().getCurrentPermission(6);
        Utilities.mandate(updateCourseBtn,insertCourseBtn , deleteCourseBtn ,6, Utilities.convertTOBase2(permissionType)); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        btnSearch = new javax.swing.JButton();
        search_textField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        updateCourseBtn = new javax.swing.JButton();
        deleteCourseBtn = new javax.swing.JButton();
        insertCourseBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        courseTable = new javax.swing.JTable();
        insertPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        codelapel = new javax.swing.JLabel();
        namelapel = new javax.swing.JLabel();
        Department_ComboBox = new javax.swing.JComboBox();
        Departmentlapel = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        code_textField = new javax.swing.JTextField();
        name_textField = new javax.swing.JTextField();
        prefered_ComboBox = new javax.swing.JComboBox();
        Departmentlapel1 = new javax.swing.JLabel();
        hours_perWeak = new javax.swing.JTextField();
        namelapel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descrption = new javax.swing.JTextArea();
        Departmentlapel2 = new javax.swing.JLabel();

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        search_textField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        search_textField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Course Screen ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Search");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Courses", 0, 0, new java.awt.Font("Tekton Pro Cond", 1, 36))); // NOI18N

        updateCourseBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateCourseBtn.setText("Update");
        updateCourseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateCourseBtnMouseClicked(evt);
            }
        });

        deleteCourseBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteCourseBtn.setText("Delete");
        deleteCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCourseBtnActionPerformed(evt);
            }
        });

        insertCourseBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        insertCourseBtn.setText("Insert New ");
        insertCourseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertCourseBtnMouseClicked(evt);
            }
        });

        courseTable.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        courseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Code", "Lecture Time ", "Department", "preferred location type"
            }
        ));
        courseTable.setRowHeight(30);
        courseTable.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                courseTableAncestorResized(evt);
            }
        });
        jScrollPane1.setViewportView(courseTable);
        courseTable.getColumnModel().getColumn(0).setHeaderValue("Name");
        courseTable.getColumnModel().getColumn(1).setHeaderValue("Code");
        courseTable.getColumnModel().getColumn(2).setHeaderValue("Lecture Time ");
        courseTable.getColumnModel().getColumn(3).setHeaderValue("Department");
        courseTable.getColumnModel().getColumn(4).setHeaderValue("preferred location type");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(updateCourseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(103, 103, 103)
                        .addComponent(deleteCourseBtn)
                        .addGap(112, 112, 112)
                        .addComponent(insertCourseBtn))
                    .addComponent(jScrollPane1)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateCourseBtn)
                    .addComponent(deleteCourseBtn)
                    .addComponent(insertCourseBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
                .addContainerGap())
        );

        insertPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Course Insert");

        codelapel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        codelapel.setText("Code");

        namelapel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        namelapel.setText("Name");

        Department_ComboBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        Departmentlapel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Departmentlapel.setText("Department ");

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });

        code_textField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        name_textField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        prefered_ComboBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        Departmentlapel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Departmentlapel1.setText("pref_Space");

        hours_perWeak.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        namelapel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        namelapel1.setText("Hours per Week");

        descrption.setColumns(20);
        descrption.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descrption.setRows(5);
        jScrollPane2.setViewportView(descrption);

        Departmentlapel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Departmentlapel2.setText("Description");

        javax.swing.GroupLayout insertPanelLayout = new javax.swing.GroupLayout(insertPanel);
        insertPanel.setLayout(insertPanelLayout);
        insertPanelLayout.setHorizontalGroup(
            insertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(insertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertPanelLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(insertPanelLayout.createSequentialGroup()
                        .addGroup(insertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(insertPanelLayout.createSequentialGroup()
                                .addComponent(Departmentlapel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(insertPanelLayout.createSequentialGroup()
                                .addComponent(Departmentlapel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(prefered_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(insertPanelLayout.createSequentialGroup()
                                .addGroup(insertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(codelapel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namelapel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namelapel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(insertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(code_textField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                                    .addComponent(name_textField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(hours_perWeak)))
                            .addGroup(insertPanelLayout.createSequentialGroup()
                                .addComponent(Departmentlapel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Department_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(insertPanelLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        insertPanelLayout.setVerticalGroup(
            insertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(insertPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(25, 25, 25)
                .addGroup(insertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codelapel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(code_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(insertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(namelapel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(insertPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(name_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(insertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hours_perWeak, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namelapel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(insertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Department_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Departmentlapel))
                .addGap(34, 34, 34)
                .addGroup(insertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prefered_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Departmentlapel1))
                .addGroup(insertPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(insertPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(insertPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(Departmentlapel2)))
                .addGap(57, 57, 57)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(468, 468, 468))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(search_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(btnSearch))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(insertPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(search_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(insertPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }//GEN-END:initComponents

    private void courseTableAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_courseTableAncestorResized
        // TODO add your handling code here:
    }//GEN-LAST:event_courseTableAncestorResized

     
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
     
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
    insertPanel.setVisible(false);
    if (search_textField != null){
        
        CourseDto course = new CourseDto();
        course.setCode(search_textField.getText());
       if (courseobjBao.SearchCourse(course)==null)
           JOptionPane.showMessageDialog(this, "not found");
       else 
            courseTableReset(courseobjBao.SearchCourse(course));
        
        }
    else 
        courseTableReset(courseobjBao.listCourses());
    }//GEN-LAST:event_btnSearchMouseClicked

    private void insertCourseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertCourseBtnMouseClicked
        insertPanel.setVisible(true);
        updateFlag = false ;
        code_textField.setEnabled(true);
 
        
    }//GEN-LAST:event_insertCourseBtnMouseClicked

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
    
     DepartmentDto department = new DepartmentDto();
     department.setDepartment_id(allDepartments.get(Department_ComboBox.getSelectedIndex()).getDepartment_id());


    CourseDto course = new CourseDto();
    course.setName(name_textField.getText());
    course.setCode(code_textField.getText());
        try {
            course.setHoursperWeak(Integer.parseInt(hours_perWeak.getText()));
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Hours should intered as a numeric value");
        }
    course.setDescription(descrption.getText());

    try {
            course.setHoursperWeak(Integer.parseInt(hours_perWeak.getText()));

        } catch (NumberFormatException nfe) {
           JOptionPane.showMessageDialog(this, "hours per weak should be a number");
        }
    
    course.setNeededLocType(allLocationType.get(prefered_ComboBox.getSelectedIndex()));
    
   
    if(updateFlag)
    { course.setCode( courseTable.getValueAt(courseTable.getSelectedRow(), 1).toString() );
      course.setUpdate_Date(new Date(System.currentTimeMillis()) );
      course.setUpdatedBy(LoginEngine.currentUser);
     }
    else 
    { course.setUpdate_Date(new Date(System.currentTimeMillis()) );
      course.setUpdatedBy(LoginEngine.currentUser);
      course.setInertion_Date(new Date(System.currentTimeMillis()) );
      course.setInsertedBy(LoginEngine.currentUser);
      course.setCode(code_textField.getText());
     }
  
    course.setDepartment(allDepartments.get(Department_ComboBox.getSelectedIndex()));
  
  
  
                 if (courseobjBao.saveCourse(course)) {
                          JOptionPane.showMessageDialog(this, "Course Saved ");
                          insertPanel.setVisible(false);
                          courseTableReset(courseobjBao.listCourses());

                }
                 else
                      JOptionPane.showMessageDialog(this,
                                   "Can not insert or update Ther are a problem please check entered data ");


    
    
    
    }//GEN-LAST:event_btnSaveMouseClicked

    private void deleteCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCourseBtnActionPerformed
         code_textField.setEnabled(true);
    
        if(courseTable.getSelectedRow() >=0)
        {
            // get the id value of the selected row 
            String selectedCourse=  courseTable.getValueAt(courseTable.getSelectedRow(), 1).toString() ;
            CourseDto selectedCourse_Delete = new CourseDto(); // this course i want to delete
            selectedCourse_Delete.setCode(selectedCourse);
            int msg=  JOptionPane.showConfirmDialog(this, "are you sure you need to delete ");
                         if (msg == JOptionPane.OK_OPTION)
                         {
            if (courseobjBao.deleteCourse(selectedCourse_Delete)) {
                JOptionPane.showMessageDialog(this , "deleted successfully");
                courseTableReset(courseobjBao.listCourses() );
            }
            
            else
               JOptionPane.showMessageDialog(this, "Can not delete may be deleted using another Course "); }   
        }
        else JOptionPane.showMessageDialog(this, "Select a Course to Delete");
      
    }//GEN-LAST:event_deleteCourseBtnActionPerformed

    private void updateCourseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateCourseBtnMouseClicked

    if (courseTable.getSelectedRow() >= 0) {


        code_textField.setText(courseTable.getValueAt(courseTable.getSelectedRow(), 1).toString());
       
        name_textField.setText(courseTable.getValueAt(courseTable.getSelectedRow(), 0).toString());
        updateFlag = true ;
        code_textField.setEnabled(false);
        insertPanel.setVisible(true);
        
        
    } else
        JOptionPane.showMessageDialog(this, "please select a course to update");
    
    
    }//GEN-LAST:event_updateCourseBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Department_ComboBox;
    private javax.swing.JLabel Departmentlapel;
    private javax.swing.JLabel Departmentlapel1;
    private javax.swing.JLabel Departmentlapel2;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JTextField code_textField;
    private javax.swing.JLabel codelapel;
    private javax.swing.JTable courseTable;
    private javax.swing.JButton deleteCourseBtn;
    private javax.swing.JTextArea descrption;
    private javax.swing.JTextField hours_perWeak;
    private javax.swing.JButton insertCourseBtn;
    private javax.swing.JPanel insertPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField name_textField;
    private javax.swing.JLabel namelapel;
    private javax.swing.JLabel namelapel1;
    private javax.swing.JComboBox prefered_ComboBox;
    private javax.swing.JTextField search_textField;
    private javax.swing.JButton updateCourseBtn;
    // End of variables declaration//GEN-END:variables
    
    
    public void courseTableReset(List<CourseDto> courses) {
       
        Object[][] coursesArr = new Object[courses.size()][7];

        for (int i = 0; i < courses.size(); i++) {

            coursesArr[i][0] = courses.get(i).getName();
            coursesArr[i][1] = courses.get(i).getCode();
            coursesArr[i][2] = courses.get(i).getDescription();
            coursesArr[i][3] = courses.get(i).getInsertedBy();
            coursesArr[i][4] = courses.get(i).getInertion_Date();
            coursesArr[i][5] = courses.get(i).getUpdatedBy();
            coursesArr[i][6] = courses.get(i).getUpdate_Date();

           

        }
      courseTable.setModel(new javax.swing.table.DefaultTableModel(coursesArr, new String[] {
                                                                     "Name", "code" ,"s per Description","Inserted By",
 "  Insertion Date", "Updated By", "Update Date"
            }
                                                                   ));
    }
    
    
    void listComboDepartment(List<DepartmentDto> dep) {
        for (int i = 0; i < dep.size(); i++) {
            Department_ComboBox.addItem(dep.get(i).getName());
           }
        }
    
    void listComboLocation(List<LocationTypeDto> locs) {
        for (int i = 0; i < locs.size(); i++) {
            prefered_ComboBox.addItem(locs.get(i).getCode());
           }
        }
}
