
package com.fym.lta.ui;

import com.fym.lta.bao.BaoFactory;
import com.fym.lta.bao.CourseBao;
import com.fym.lta.bao.LoginEngine;
import com.fym.lta.dto.CourseDto;
import com.fym.lta.dto.DepartmentDto;
import com.fym.lta.dto.LocationTypeDto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.JOptionPane;

/**
 *
 * @author Mina
 */
public class CourseScreen extends javax.swing.JPanel
{

private CourseBao courseobjBao = new BaoFactory().createCourseBao();

    boolean updateFlag = false ;
    
    

    List<DepartmentDto> allDepartments = new BaoFactory().createDepartmentBao().listDepartment();
    
    // how to get location types in combo box 
    List<LocationTypeDto> allLocationType = new BaoFactory().createLocationTypeBao().listLocationType();

 
   
    /** Creates new form CourseSearch */
    public CourseScreen() 

{ 
        initComponents();
        if(allDepartments!=null)
        listComboDepartment(allDepartments);
        if (courseobjBao.listCourses()!= null)
            courseTableReset(courseobjBao.listCourses());
        if(allLocationType!=null)
            listComboLocation(allLocationType) ; 
        insertPanel.setVisible(false);
        int permissionType = new BaoFactory().createScreenBao().getCurrentPermission(6);
        Utilities.mandate(updateCourseBtn,insertCourseBtn , deleteCourseBtn ,6, Utilities.convertTOBase2(permissionType)); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        popup = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        btnSearch = new javax.swing.JButton();
        search_textField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        courseTable = new javax.swing.JTable();
        insertPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        codelapel = new javax.swing.JLabel();
        namelapel = new javax.swing.JLabel();
        Department_ComboBox = new javax.swing.JComboBox();
        Departmentlapel = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        code_textField = new javax.swing.JTextField();
        name_textField = new javax.swing.JTextField();
        prefered_ComboBox = new javax.swing.JComboBox();
        Departmentlapel1 = new javax.swing.JLabel();
        hours_perWeak = new javax.swing.JTextField();
        namelapel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descrption = new javax.swing.JTextArea();
        Departmentlapel2 = new javax.swing.JLabel();
        updateCourseBtn = new javax.swing.JButton();
        deleteCourseBtn = new javax.swing.JButton();
        insertCourseBtn = new javax.swing.JButton();

        jMenuItem1.setText("Print");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        popup.add(jMenuItem1);

        jMenuItem2.setText("Expor to PDF");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        popup.add(jMenuItem2);

        jMenuItem3.setText("Export to XLX");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        popup.add(jMenuItem3);

        jMenuItem5.setText("Hide Insertion Panel");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        popup.add(jMenuItem5);

        jMenuItem6.setText("Import Sheet");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        popup.add(jMenuItem6);

        setBackground(new java.awt.Color(0, 0, 0));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearch.setBackground(new java.awt.Color(0, 0, 0));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon("C:\\Oracle\\Middleware\\LTA\\icons\\search.png")); // NOI18N
        btnSearch.setBorder(null);
        btnSearch.setBorderPainted(false);
        btnSearch.setPreferredSize(new java.awt.Dimension(70, 30));
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 80, 50));

        search_textField.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        search_textField.setBorder(null);
        search_textField.setMaximumSize(new java.awt.Dimension(2, 20));
        search_textField.setMinimumSize(new java.awt.Dimension(2, 20));
        search_textField.setPreferredSize(new java.awt.Dimension(2, 20));
        add(search_textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 229, 33));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Oracle\\Middleware\\LTA\\icons\\course.png")); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 280, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Oracle\\Middleware\\LTA\\icons\\search2.png")); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 140, 30));

        cPanel.setBackground(new java.awt.Color(0, 0, 0));
        cPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Courses", 0, 0, new java.awt.Font("Tekton Pro Cond", 2, 24), new java.awt.Color(204, 240, 240))); // NOI18N

        courseTable.setBackground(new java.awt.Color(51, 98, 114));
        courseTable.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N
        courseTable.setForeground(new java.awt.Color(255, 255, 255));
        courseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Code", "Lecture Time ", "Department", "preferred location type"
            }
        ));
        courseTable.setRowHeight(25);
        courseTable.setSelectionBackground(new java.awt.Color(22, 224, 236));
        courseTable.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                courseTableAncestorResized(evt);
            }
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
        });
        jScrollPane1.setViewportView(courseTable);
        courseTable.getColumnModel().getColumn(0).setHeaderValue("Name");
        courseTable.getColumnModel().getColumn(1).setHeaderValue("Code");
        courseTable.getColumnModel().getColumn(2).setHeaderValue("Lecture Time ");
        courseTable.getColumnModel().getColumn(3).setHeaderValue("Department");
        courseTable.getColumnModel().getColumn(4).setHeaderValue("preferred location type");

        javax.swing.GroupLayout cPanelLayout = new javax.swing.GroupLayout(cPanel);
        cPanel.setLayout(cPanelLayout);
        cPanelLayout.setHorizontalGroup(
            cPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        cPanelLayout.setVerticalGroup(
            cPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(cPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 550, 500));

        insertPanel.setBackground(new java.awt.Color(51, 98, 114));
        insertPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        insertPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Course Insert");
        insertPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 31, -1, -1));

        codelapel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        codelapel.setForeground(new java.awt.Color(255, 255, 255));
        codelapel.setText("Code");
        insertPanel.add(codelapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 78, 61, 34));

        namelapel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        namelapel.setForeground(new java.awt.Color(255, 255, 255));
        namelapel.setText("Name");
        insertPanel.add(namelapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 139, 77, 33));

        Department_ComboBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        insertPanel.add(Department_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 269, 319, 52));

        Departmentlapel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Departmentlapel.setForeground(new java.awt.Color(255, 255, 255));
        Departmentlapel.setText("Department ");
        insertPanel.add(Departmentlapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 290, -1, -1));

        btnSave.setBackground(new java.awt.Color(51, 98, 114));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon("C:\\Oracle\\Middleware\\LTA\\icons\\save.png")); // NOI18N
        btnSave.setBorderPainted(false);
        btnSave.setMaximumSize(new java.awt.Dimension(60, 30));
        btnSave.setMinimumSize(new java.awt.Dimension(60, 30));
        btnSave.setPreferredSize(new java.awt.Dimension(60, 30));
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        insertPanel.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, 140, 60));

        code_textField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        code_textField.setBorder(null);
        insertPanel.add(code_textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 78, 319, 35));

        name_textField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name_textField.setBorder(null);
        insertPanel.add(name_textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 131, 319, 33));

        prefered_ComboBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        insertPanel.add(prefered_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 355, 319, 52));

        Departmentlapel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Departmentlapel1.setForeground(new java.awt.Color(255, 255, 255));
        Departmentlapel1.setText("pref_Space");
        insertPanel.add(Departmentlapel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 376, -1, -1));

        hours_perWeak.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hours_perWeak.setBorder(null);
        insertPanel.add(hours_perWeak, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 200, 319, 32));

        namelapel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        namelapel1.setForeground(new java.awt.Color(255, 255, 255));
        namelapel1.setText("Hours per Week");
        insertPanel.add(namelapel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 200, 159, 33));

        descrption.setColumns(20);
        descrption.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        descrption.setRows(5);
        descrption.setBorder(null);
        jScrollPane2.setViewportView(descrption);

        insertPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 442, 319, -1));

        Departmentlapel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Departmentlapel2.setForeground(new java.awt.Color(255, 255, 255));
        Departmentlapel2.setText("Description");
        insertPanel.add(Departmentlapel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 467, -1, -1));

        add(insertPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 540, 620));

        updateCourseBtn.setBackground(new java.awt.Color(0, 0, 0));
        updateCourseBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateCourseBtn.setIcon(new javax.swing.ImageIcon("C:\\Oracle\\Middleware\\LTA\\icons\\update.png")); // NOI18N
        updateCourseBtn.setBorder(null);
        updateCourseBtn.setBorderPainted(false);
        updateCourseBtn.setMaximumSize(new java.awt.Dimension(73, 25));
        updateCourseBtn.setMinimumSize(new java.awt.Dimension(73, 25));
        updateCourseBtn.setPreferredSize(new java.awt.Dimension(73, 25));
        updateCourseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateCourseBtnMouseClicked(evt);
            }
        });
        add(updateCourseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 80, 30));

        deleteCourseBtn.setBackground(new java.awt.Color(0, 0, 0));
        deleteCourseBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteCourseBtn.setIcon(new javax.swing.ImageIcon("C:\\Oracle\\Middleware\\LTA\\icons\\delete.png")); // NOI18N
        deleteCourseBtn.setBorder(null);
        deleteCourseBtn.setBorderPainted(false);
        deleteCourseBtn.setMaximumSize(new java.awt.Dimension(73, 25));
        deleteCourseBtn.setMinimumSize(new java.awt.Dimension(73, 25));
        deleteCourseBtn.setPreferredSize(new java.awt.Dimension(73, 25));
        deleteCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCourseBtnActionPerformed(evt);
            }
        });
        add(deleteCourseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 80, 30));

        insertCourseBtn.setBackground(new java.awt.Color(0, 0, 0));
        insertCourseBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        insertCourseBtn.setIcon(new javax.swing.ImageIcon("C:\\Oracle\\Middleware\\LTA\\icons\\insert.png")); // NOI18N
        insertCourseBtn.setBorder(null);
        insertCourseBtn.setBorderPainted(false);
        insertCourseBtn.setMaximumSize(new java.awt.Dimension(110, 25));
        insertCourseBtn.setMinimumSize(new java.awt.Dimension(110, 25));
        insertCourseBtn.setPreferredSize(new java.awt.Dimension(110, 25));
        insertCourseBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertCourseBtnMouseClicked(evt);
            }
        });
        add(insertCourseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 120, 30));
    }//GEN-END:initComponents

    private void courseTableAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_courseTableAncestorResized
        // TODO add your handling code here:
    }//GEN-LAST:event_courseTableAncestorResized

     
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
     
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
    insertPanel.setVisible(false);
    if (search_textField != null){
        
        CourseDto course = new CourseDto();
        course.setCode(search_textField.getText());
       if (courseobjBao.SearchCourse(course)==null)
           JOptionPane.showMessageDialog(this, "not found");
       else 
            courseTableReset(courseobjBao.SearchCourse(course));
        
        }
    else 
        courseTableReset(courseobjBao.listCourses());
    }//GEN-LAST:event_btnSearchMouseClicked

    private void insertCourseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertCourseBtnMouseClicked
        insertPanel.setVisible(true);
        updateFlag = false ;
        code_textField.setEnabled(true);
 
        
    }//GEN-LAST:event_insertCourseBtnMouseClicked

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
    
     DepartmentDto department = new DepartmentDto();
     department.setDepartment_id(allDepartments.get(Department_ComboBox.getSelectedIndex()).getDepartment_id());


    CourseDto course = new CourseDto();
    course.setName(name_textField.getText());
    course.setCode(code_textField.getText());
        try {
            course.setHoursperWeak(Integer.parseInt(hours_perWeak.getText()));
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Hours should intered as a numeric value");
        }
    course.setDescription(descrption.getText());

    try {
            course.setHoursperWeak(Integer.parseInt(hours_perWeak.getText()));

        } catch (NumberFormatException nfe) {
           JOptionPane.showMessageDialog(this, "hours per weak should be a number");
        }
    
    course.setNeededLocType(allLocationType.get(prefered_ComboBox.getSelectedIndex()));
    
   
    if(updateFlag)
    { course.setCode( courseTable.getValueAt(courseTable.getSelectedRow(), 1).toString() );
      course.setUpdate_Date(new Date(System.currentTimeMillis()) );
      course.setUpdatedBy(LoginEngine.currentUser);
     }
    else 
    { course.setUpdate_Date(new Date(System.currentTimeMillis()) );
      course.setUpdatedBy(LoginEngine.currentUser);
      course.setInertion_Date(new Date(System.currentTimeMillis()) );
      course.setInsertedBy(LoginEngine.currentUser);
      course.setCode(code_textField.getText());
     }
  
    course.setDepartment(allDepartments.get(Department_ComboBox.getSelectedIndex()));
    
    // we used array list to avoid the driver problems when we reading from xlx sheet 
    List<CourseDto> courses = new ArrayList<>();
       courses.add(course);
  
                 if (courseobjBao.saveCourses(courses)) {
                          JOptionPane.showMessageDialog(this, "Course Saved ");
                      
                          courseTableReset(courseobjBao.listCourses());

                }
                 else
                      JOptionPane.showMessageDialog(this,
                                   "Can not insert or update Ther are a problem please check entered data ");


    
    
    
    }//GEN-LAST:event_btnSaveMouseClicked

    private void deleteCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCourseBtnActionPerformed
         code_textField.setEnabled(true);
    
        if(courseTable.getSelectedRow() >=0)
        {
            // get the id value of the selected row 
            String selectedCourse=  courseTable.getValueAt(courseTable.getSelectedRow(), 1).toString() ;
            CourseDto selectedCourse_Delete = new CourseDto(); // this course i want to delete
            selectedCourse_Delete.setCode(selectedCourse);
            int msg=  JOptionPane.showConfirmDialog(this, "are you sure you need to delete ");
                         if (msg == JOptionPane.OK_OPTION)
                         {
            if (courseobjBao.deleteCourse(selectedCourse_Delete)) {
                JOptionPane.showMessageDialog(this , "deleted successfully");
                courseTableReset(courseobjBao.listCourses() );
            }
            
            else
               JOptionPane.showMessageDialog(this, "Can not delete may be deleted using another Course "); }   
        }
        else JOptionPane.showMessageDialog(this, "Select a Course to Delete");
      
    }//GEN-LAST:event_deleteCourseBtnActionPerformed

    private void updateCourseBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateCourseBtnMouseClicked

    if (courseTable.getSelectedRow() >= 0) {


        code_textField.setText(courseTable.getValueAt(courseTable.getSelectedRow(), 1).toString());
       
        name_textField.setText(courseTable.getValueAt(courseTable.getSelectedRow(), 0).toString());
        updateFlag = true ;
        code_textField.setEnabled(false);
        insertPanel.setVisible(true);
        
        
    } else
        JOptionPane.showMessageDialog(this, "please select a course to update");
    
    
    }//GEN-LAST:event_updateCourseBtnMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Utilities.printRecord(cPanel);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        Utilities.export_PDF(courseTable);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        Utilities.export_XLX(courseTable);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased

    if(evt.isPopupTrigger())
       {
       popup.show(this, evt.getX(), evt.getY());    
       }
    }//GEN-LAST:event_formMouseReleased

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        insertPanel.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed

     //TableReset(readlist());
    }//GEN-LAST:event_jMenuItem6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Department_ComboBox;
    private javax.swing.JLabel Departmentlapel;
    private javax.swing.JLabel Departmentlapel1;
    private javax.swing.JLabel Departmentlapel2;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel cPanel;
    private javax.swing.JTextField code_textField;
    private javax.swing.JLabel codelapel;
    private javax.swing.JTable courseTable;
    private javax.swing.JButton deleteCourseBtn;
    private javax.swing.JTextArea descrption;
    private javax.swing.JTextField hours_perWeak;
    private javax.swing.JButton insertCourseBtn;
    private javax.swing.JPanel insertPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField name_textField;
    private javax.swing.JLabel namelapel;
    private javax.swing.JLabel namelapel1;
    private javax.swing.JPopupMenu popup;
    private javax.swing.JComboBox prefered_ComboBox;
    private javax.swing.JTextField search_textField;
    private javax.swing.JButton updateCourseBtn;
    // End of variables declaration//GEN-END:variables
    
    
    public void courseTableReset(List<CourseDto> courses) {
       
        Object[][] coursesArr = new Object[courses.size()][8];

        for (int i = 0; i < courses.size(); i++) {

            coursesArr[i][0] = courses.get(i).getName();
            coursesArr[i][1] = courses.get(i).getCode();
            coursesArr[i][2] = courses.get(i).getDescription();
            coursesArr[i][3] = courses.get(i).getHoursperWeak();
            coursesArr[i][4] = courses.get(i).getInsertedBy();
            coursesArr[i][5] = courses.get(i).getInertion_Date();
            coursesArr[i][6] = courses.get(i).getUpdatedBy();
            coursesArr[i][7] = courses.get(i).getUpdate_Date();

           

        }
      courseTable.setModel(new javax.swing.table.DefaultTableModel(coursesArr, new String[] {
                                                                     "Name", "code" ,"Description","Hours per Weak","Inserted By",
 "  Insertion Date", "Updated By", "Update Date"
            }
                                                                   ));
    }
    
    
    void listComboDepartment(List<DepartmentDto> dep) {
        for (int i = 0; i < dep.size(); i++) {
            Department_ComboBox.addItem(dep.get(i).getName());
           }
        }
    
    void listComboLocation(List<LocationTypeDto> locs) {
        for (int i = 0; i < locs.size(); i++) {
            prefered_ComboBox.addItem(locs.get(i).getCode());
           }
        }
}
