package com.fym.lta.ui;

import com.fym.lta.bao.BaoFactory;
import com.fym.lta.bao.EquipmentBao;
import com.fym.lta.bao.LoginEngine;
import com.fym.lta.common.LTAException;
import com.fym.lta.dto.EquipmentDto;
import com.fym.lta.dto.LocationDto;

import java.util.Date;
import java.util.List;

import javax.swing.JOptionPane;

/**
 *
 * @author Nada
 */
public class EquipmentScreen extends javax.swing.JPanel {
    
    //To create a refrence from EquipmentBao 
    private EquipmentBao Equipmentbusiness  = new BaoFactory().createEquipmentBao();
    
    //To Get list of  locations  to set comboBox items 
    List<LocationDto> All_locations = new BaoFactory().createLocationBao().ListAll();
  
    // flag , if it equals 1 we update, if zero we insert 
    private int Equipment_idUpdate ;
    
    
    /*To add comboBox items
     We get a list of saved items in Database*/  
    void listComboLocations(List<LocationDto> location) {
        if(location!=null) {
    for (int i = 0; i < location.size(); i++) {
      location_combo.addItem(location.get(i).getCode()); }
    }
    }
    // To Set the retrieved data from database into the locationTable// 
    private void setTableModel(List<EquipmentDto> equipment){
        Object [][] equipmentArr = new Object [equipment.size()][9];
        for(int i =0;i<equipment.size();i++){
            equipmentArr[i][0] = equipment.get(i).getCode();
            equipmentArr[i][1] = equipment.get(i).getType();
            equipmentArr[i][2] = equipment.get(i).getLifSpan();
            equipmentArr[i][3] = equipment.get(i).getStartingTime();
            equipmentArr[i][4] = equipment.get(i).getLocation_equipment().getCode();     
            equipmentArr[i][5] = equipment.get(i).getInsertedBy();
            equipmentArr[i][6] = equipment.get(i).getInertion_Date();
            equipmentArr[i][7] = equipment.get(i).getUpdatedBy();
            equipmentArr[i][8] = equipment.get(i).getUpdate_Date();      
        }
        EquipmentTable.setModel(new javax.swing.table.DefaultTableModel(equipmentArr,
            new String [] {
                 "Equipment Code" , "Equipment Type", "Life Span" ,"Starting time","Location" ,"Inserted By" , "Insertion Date" , "Updated By","Update Date"
            }
        ));   }  
    
    /** Creates new form EquipmentScreen */
    public EquipmentScreen() {
        initComponents();
        if(Equipmentbusiness.ListAll()!=null)
        setTableModel(Equipmentbusiness.ListAll());
        listComboLocations(All_locations);
        DefineEquipment.setVisible(false);
        int permissionType = new BaoFactory().createScreenBao().getCurrentPermission(7);
        Utilities.mandate(update ,insert , delete ,7, Utilities.convertTOBase2(permissionType)); 
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        popup = new javax.swing.JPopupMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        ePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EquipmentTable = new javax.swing.JTable();
        insert = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        DefineEquipment = new javax.swing.JPanel();
        location_combo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        type = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        years_number = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jMenuItem2.setText("Print");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        popup.add(jMenuItem2);

        jMenuItem3.setText("Expor to PDF");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        popup.add(jMenuItem3);

        jMenuItem4.setText("Export to XLX");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        popup.add(jMenuItem4);

        jMenuItem5.setText("Hide Insertion Panel");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        popup.add(jMenuItem5);

        setBackground(new java.awt.Color(0, 0, 0));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ePanel.setBackground(new java.awt.Color(0, 0, 0));
        ePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 240, 240)), "Equipments", 0, 0, new java.awt.Font("Tekton Pro Cond", 2, 24), new java.awt.Color(204, 240, 240))); // NOI18N
        ePanel.setPreferredSize(new java.awt.Dimension(400, 400));

        EquipmentTable.setBackground(new java.awt.Color(51, 98, 114));
        EquipmentTable.setFont(new java.awt.Font("Tekton Pro", 0, 12)); // NOI18N
        EquipmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12"
            }
        ));
        EquipmentTable.setMaximumSize(new java.awt.Dimension(512, 512));
        EquipmentTable.setMinimumSize(new java.awt.Dimension(512, 512));
        EquipmentTable.setPreferredSize(new java.awt.Dimension(512, 512));
        EquipmentTable.setRowHeight(30);
        EquipmentTable.setSelectionBackground(new java.awt.Color(22, 224, 236));
        jScrollPane1.setViewportView(EquipmentTable);
        EquipmentTable.getColumnModel().getColumn(0).setHeaderValue("Title 1");
        EquipmentTable.getColumnModel().getColumn(1).setHeaderValue("Title 2");
        EquipmentTable.getColumnModel().getColumn(2).setHeaderValue("Title 3");
        EquipmentTable.getColumnModel().getColumn(3).setHeaderValue("Title 4");
        EquipmentTable.getColumnModel().getColumn(4).setHeaderValue("Title 5");
        EquipmentTable.getColumnModel().getColumn(5).setHeaderValue("Title 6");
        EquipmentTable.getColumnModel().getColumn(6).setHeaderValue("Title 7");
        EquipmentTable.getColumnModel().getColumn(7).setHeaderValue("Title 8");
        EquipmentTable.getColumnModel().getColumn(8).setHeaderValue("Title 9");
        EquipmentTable.getColumnModel().getColumn(9).setHeaderValue("Title 10");
        EquipmentTable.getColumnModel().getColumn(10).setHeaderValue("Title 11");
        EquipmentTable.getColumnModel().getColumn(11).setHeaderValue("Title 12");

        javax.swing.GroupLayout ePanelLayout = new javax.swing.GroupLayout(ePanel);
        ePanel.setLayout(ePanelLayout);
        ePanelLayout.setHorizontalGroup(
            ePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        ePanelLayout.setVerticalGroup(
            ePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE))
        );

        add(ePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 620, 360));

        insert.setBackground(new java.awt.Color(0, 0, 0));
        insert.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        insert.setIcon(new javax.swing.ImageIcon("C:\\Oracle\\Middleware\\LTA\\icons\\insert.png")); // NOI18N
        insert.setBorderPainted(false);
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        add(insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 120, 30));

        delete.setBackground(new java.awt.Color(0, 0, 0));
        delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon("C:\\Oracle\\Middleware\\LTA\\icons\\delete.png")); // NOI18N
        delete.setBorderPainted(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 80, 30));

        update.setBackground(new java.awt.Color(0, 0, 0));
        update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon("C:\\Oracle\\Middleware\\LTA\\icons\\update.png")); // NOI18N
        update.setBorderPainted(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 90, 30));

        jTextField1.setBorder(null);
        jTextField1.setMaximumSize(new java.awt.Dimension(2, 20));
        jTextField1.setMinimumSize(new java.awt.Dimension(2, 20));
        jTextField1.setPreferredSize(new java.awt.Dimension(2, 20));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 230, 30));

        search.setBackground(new java.awt.Color(0, 0, 0));
        search.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        search.setIcon(new javax.swing.ImageIcon("C:\\Oracle\\Middleware\\LTA\\icons\\search.png")); // NOI18N
        search.setBorderPainted(false);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 80, 50));

        DefineEquipment.setBackground(new java.awt.Color(51, 98, 114));
        DefineEquipment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DefineEquipment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        location_combo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        location_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                location_comboActionPerformed(evt);
            }
        });
        DefineEquipment.add(location_combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 44, 183, 42));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Location  ");
        DefineEquipment.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 55, 113, 22));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Code");
        DefineEquipment.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 123, 62, 29));

        code.setBorder(null);
        DefineEquipment.add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 124, 180, 29));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Type");
        DefineEquipment.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 208, 72, 29));

        type.setBorder(null);
        DefineEquipment.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 209, 180, 29));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Number of used years");
        DefineEquipment.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 274, 206, 29));

        years_number.setBorder(null);
        DefineEquipment.add(years_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 275, 180, 29));

        save.setBackground(new java.awt.Color(51, 98, 114));
        save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save.setIcon(new javax.swing.ImageIcon("C:\\Oracle\\Middleware\\LTA\\icons\\save.png")); // NOI18N
        save.setBorderPainted(false);
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        DefineEquipment.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 140, 60));

        add(DefineEquipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 160, 490, 410));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Oracle\\Middleware\\LTA\\icons\\search2.png")); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 150, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Equipment Screen ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 280, 50));
    }//GEN-END:initComponents

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        clearData();
       Equipment_idUpdate = 0;
        DefineEquipment.setVisible(true);

        // UsersScreen.createPopupMenu(new DefineLocation());
    }//GEN-LAST:event_insertActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
    if (EquipmentTable.getSelectedRow() >= 0) {
        try{
             DefineEquipment.setVisible(false);
             String code = EquipmentTable.getValueAt(EquipmentTable.getSelectedRow(), 0).toString();
            EquipmentDto selected_Equipment = new EquipmentDto(); // selected Equipment, To delete.
            selected_Equipment.setCode(code);
            
                int msg=  JOptionPane.showConfirmDialog(this, "are you sure you need to delete ");
                               if (msg == JOptionPane.OK_OPTION)
                               {  
            if (Equipmentbusiness.deleteEquipment(selected_Equipment)) {  //if returned true, Equipment will be deleted
                JOptionPane.showMessageDialog(this, "Equipment is Deleted Successfully");
                setTableModel(Equipmentbusiness.ListAll());
                EquipmentTable.repaint() ;
            }else
            JOptionPane.showMessageDialog(this, "Can't delete this equipment ! ");
            }}
        catch(Exception e){
            e.printStackTrace();
        }
    }
    else {  // if no equipment is selected on the table
       JOptionPane.showMessageDialog(this, "you should select an Equipment to delete  ");
    }
        
       
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        if (EquipmentTable.getSelectedRow()>=0)
        {    // No need to update Id, so we hide it//
           // id.setVisible(false); 
            //jLabel1.setVisible(false);
            try{

           // id.setText(EquipmentTable.getValueAt(EquipmentTable.getSelectedRow(), 0).toString());
            code.setText(EquipmentTable.getValueAt(EquipmentTable.getSelectedRow(), 0).toString());
            type.setText(EquipmentTable.getValueAt(EquipmentTable.getSelectedRow(), 1).toString());
            years_number.setText(EquipmentTable.getValueAt(EquipmentTable.getSelectedRow(), 2).toString());       
            DefineEquipment.setVisible(true);
                
            // flag , if it equals 1 we update, if zero we insert     
            Equipment_idUpdate = 1;    
            
        }catch(Exception e){
            e.printStackTrace();
        }
        }
        else JOptionPane.showMessageDialog(this, " you should select an Equipment to update ");

    }//GEN-LAST:event_updateActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed

          try {
            DefineEquipment.setVisible(false);
              if (jTextField1.getText()!= null){
                setTableModel(Equipmentbusiness.SearchEquipment(jTextField1.getText()));
                 jTextField1.setText(null);}
            else
            setTableModel(Equipmentbusiness.ListAll());

        } catch(java.lang.NullPointerException e){
        JOptionPane.showMessageDialog(this, "This Equipment isn't existed ");    
        }
          catch (Exception e) {
            // TODO: Add catch code
            e.printStackTrace();
        }
    }//GEN-LAST:event_searchActionPerformed

    private void location_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_location_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_location_comboActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        try{
            //Create Dto Objects to get data from UI and then pass it to Bao//
           EquipmentDto EquipmentObject = new EquipmentDto();
           LocationDto LocationObject = new LocationDto();  
           
            //To get data from UI//
            //EquipmentObject.setEquipment_id(Integer.parseInt(id.getText()));
            EquipmentObject.setType(type.getText());
            EquipmentObject.setLifSpan(Integer.parseInt(years_number.getText()));
           
            //To set id for location//
            LocationObject.setLocation_id(All_locations.get(location_combo.getSelectedIndex()).getLocation_id());
            EquipmentObject.setLocation_equipment(LocationObject);
          
            //To Check whether to insert or update data// 
       if(Equipment_idUpdate !=0){
                  
                EquipmentObject.setCode(EquipmentTable.getValueAt(EquipmentTable.getSelectedRow(), 0).toString());
                    EquipmentObject.setUpdatedBy(LoginEngine.currentUser);
                    EquipmentObject.setUpdate_Date(new Date(System.currentTimeMillis()));
            try {  if(Equipmentbusiness.updateEquipment(EquipmentObject)) {
                      JOptionPane.showMessageDialog(this, "Location Updated Successfully");
                      setTableModel(Equipmentbusiness.ListAll());}
                         
                   else
                      JOptionPane.showMessageDialog(this, "Error occured in update");} 
            catch(LTAException ex){
                   JOptionPane.showMessageDialog(this, "Error in Data base");}
            }
        else{
                        
                EquipmentObject.setCode(code.getText());
                EquipmentObject.setInsertedBy(LoginEngine.currentUser);
                EquipmentObject.setInertion_Date(new Date(System.currentTimeMillis()));
                EquipmentObject.setStartingTime(new Date(System.currentTimeMillis()));
                
             try {
               if( Equipmentbusiness.insertEquipment(EquipmentObject)){
                  JOptionPane.showMessageDialog(this, "Location Saved Successfully");
                  setTableModel(Equipmentbusiness.ListAll());}
              else
                 JOptionPane.showMessageDialog(this, "Error occured in insertion");}
            catch(LTAException ex){
                JOptionPane.showMessageDialog(this, "Error in Data base");}
        }

        } catch(java.lang.NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Error occured, There is an Error in data Type Or Some Of Data is Missed !");
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_saveActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Utilities.printRecord(ePanel);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        Utilities.export_PDF(EquipmentTable);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        Utilities.export_XLX(EquipmentTable);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased

    if(evt.isPopupTrigger())
       {
       popup.show(this, evt.getX(), evt.getY());    
       }
    }//GEN-LAST:event_formMouseReleased

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        DefineEquipment.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DefineEquipment;
    private javax.swing.JTable EquipmentTable;
    private javax.swing.JTextField code;
    private javax.swing.JButton delete;
    private javax.swing.JPanel ePanel;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox location_combo;
    private javax.swing.JPopupMenu popup;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JTextField type;
    private javax.swing.JButton update;
    private javax.swing.JTextField years_number;
    // End of variables declaration//GEN-END:variables
    
    // this method just to clear text and reset the valus on the insert panel
    void clearData() { // clear prvious data
        //id.setText(null);
        code.setText(null);
        type.setText(null);
        years_number.setText(null);
        
        // show hiden components again
       //id.setVisible(true);
       // jLabel1.setVisible(true);      
    }
    
   
}