
package com.fym.lta.ui;

import com.fym.lta.bao.BaoFactory;
import com.fym.lta.bao.LocationBao;
import com.fym.lta.bao.LoginEngine;
import com.fym.lta.dto.BuildingDto;
import com.fym.lta.dto.EquipmentDto;
import com.fym.lta.dto.FloorDto;
import com.fym.lta.dto.LocationDto;
import com.fym.lta.dto.LocationTypeDto;

import java.util.Date;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Nada
 */
public class LocationMasterScreen extends javax.swing.JPanel {
    
    //To create a refrence from LocationBao , EquipmentBao 
    private LocationBao Locationbusiness  = new BaoFactory().createLocationBao();
    
    // flag , if it equals 1 we update, if zero we insert  
    private int Location_idUpdate ;
   
    //To Get list of building , floor , location type to set comboBox items 
    List<BuildingDto> Allbuildings = new BaoFactory().createBuildingBao().listBuilding();
    List<FloorDto> Allfloors = new BaoFactory().createFloorBao().listFloor();
    List<LocationTypeDto> AlllocationTypes = new BaoFactory().createLocationTypeBao().listLocationType();
    List<EquipmentDto> AllEquipments = new BaoFactory().createEquipmentBao().ListAll();


        /*To add comboBox items
        We get a list of saved items in Database*/
     void listComboBuildings(List<BuildingDto> building) {
           for (int i = 0; i < building.size(); i++) {
               building_combo.addItem(building.get(i).getCode());
                     }
    }
     
    void listComboFloors(List<FloorDto> floor) {
          for (int i = 0; i < floor.size(); i++) {
             floor_combo.addItem(floor.get(i).getCode());
                    }
    }
    
    void listComboLocationTypes(List<LocationTypeDto> LocationType) {
          for (int i = 0; i < LocationType.size(); i++)
          {
             type_combo.addItem(LocationType.get(i).getCode());
          }
    }
    
    void listEquipments(List<EquipmentDto> Equipment) {
        if(Equipment!=null) {
        DefaultListModel list = new DefaultListModel();
          for (int i = 0; i < Equipment.size(); i++) 
          {
                 list.addElement(Equipment.get(i).getCode());  
          }
         // EquipmentList.setModel(list);
         }
    }
      
    // To Set the retrieved data from database into the locationTable//  
    private void setTableModel(List<LocationDto> location  ){
        Object [][] locationArr = new Object [location.size()][10];
        for(int i =0;i<location.size();i++){
          //  locationArr[i][0] = location.get(i).getLocation_id();
            locationArr[i][0] = location.get(i).getCode();
            locationArr[i][1] = location.get(i).getDescription();
            locationArr[i][2] = location.get(i).getCapacity();
           
            locationArr[i][3] = location.get(i).getFloor().getBuilding().getCode();
            locationArr[i][4] = location.get(i).getFloor().getCode();
            locationArr[i][5] = location.get(i).getType().getCode();
            locationArr[i][6] = location.get(i).getInsertedBy();
            locationArr[i][7] = location.get(i).getInertion_Date();
            locationArr[i][8] = location.get(i).getUpdatedBy();
            locationArr[i][9] = location.get(i).getUpdate_Date();  }    
        
        LocationTable.setModel(new javax.swing.table.DefaultTableModel(locationArr,
            new String [] {
             "Location Code" , "Description", "capacity" ,"Building", "Floor","Location Type" , "Inserted By","Insertion Date","Updated By","Update Date"
            }
        ));   }  
    
    
   
    /** Creates new form MasterScreen */
    public LocationMasterScreen() {
        initComponents();
      if(Locationbusiness.ListAll()!=null)
      setTableModel(Locationbusiness.ListAll());
        listComboBuildings(Allbuildings);
        listComboFloors(Allfloors);
        listComboLocationTypes(AlllocationTypes);
        listEquipments(AllEquipments);
        define_location.setVisible(false);
        
        // roleID = 8
        // now one step we will create an object of ScreenBao to know the current permission 
        int permissionType = new BaoFactory().createScreenBao().getCurrentPermission(8);
        Utilities.mandate(updateLocationBtn, insertLocationBtn , deleteLocationBtn ,8, Utilities.convertTOBase2(permissionType));

    }
  
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        master = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LocationTable = new javax.swing.JTable();
        insertLocationBtn = new javax.swing.JButton();
        deleteLocationBtn = new javax.swing.JButton();
        updateLocationBtn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        define_location = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        desc = new javax.swing.JTextField();
        capacity = new javax.swing.JTextField();
        building_combo = new javax.swing.JComboBox();
        floor_combo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        type_combo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 400));
        setLayout(null);

        master.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Locations ", 0, 0, new java.awt.Font("Tekton Pro Cond", 1, 36))); // NOI18N
        master.setPreferredSize(new java.awt.Dimension(400, 400));

        LocationTable.setFont(new java.awt.Font("Tekton Pro", 0, 24)); // NOI18N
        LocationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12"
            }
        ));
        LocationTable.setRowHeight(30);
        jScrollPane1.setViewportView(LocationTable);

        javax.swing.GroupLayout masterLayout = new javax.swing.GroupLayout(master);
        master.setLayout(masterLayout);
        masterLayout.setHorizontalGroup(
            masterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masterLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        masterLayout.setVerticalGroup(
            masterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, masterLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(master);
        master.setBounds(80, 332, 690, 400);

        insertLocationBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        insertLocationBtn.setText("Insert New ");
        insertLocationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertLocationBtnActionPerformed(evt);
            }
        });
        add(insertLocationBtn);
        insertLocationBtn.setBounds(560, 240, 190, 60);

        deleteLocationBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteLocationBtn.setText("Delete ");
        deleteLocationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLocationBtnActionPerformed(evt);
            }
        });
        add(deleteLocationBtn);
        deleteLocationBtn.setBounds(330, 240, 100, 60);

        updateLocationBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateLocationBtn.setText("Update  ");
        updateLocationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateLocationBtnActionPerformed(evt);
            }
        });
        add(updateLocationBtn);
        updateLocationBtn.setBounds(80, 240, 120, 60);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(70, 150, 389, 40);

        search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        add(search);
        search.setBounds(560, 140, 107, 60);

        define_location.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        define_location.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Code");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Description");

        save.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Capacity");

        building_combo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        building_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                building_comboActionPerformed(evt);
            }
        });

        floor_combo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Choose Building ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Choose Floor ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Location Type ");

        type_combo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout define_locationLayout = new javax.swing.GroupLayout(define_location);
        define_location.setLayout(define_locationLayout);
        define_locationLayout.setHorizontalGroup(
            define_locationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(define_locationLayout.createSequentialGroup()
                .addGroup(define_locationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(define_locationLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(define_locationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(define_locationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(define_locationLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(building_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(236, 236, 236)
                .addGroup(define_locationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capacity, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(define_locationLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(define_locationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(floor_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addGroup(define_locationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(define_locationLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        define_locationLayout.setVerticalGroup(
            define_locationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(define_locationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(define_locationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7))
                .addGap(15, 15, 15)
                .addGroup(define_locationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(floor_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(building_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(define_locationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(define_locationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(define_locationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capacity, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106)
                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
        );

        add(define_location);
        define_location.setBounds(810, 190, 570, 540);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Search");
        add(jLabel8);
        jLabel8.setBounds(70, 90, 196, 48);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setText("Locations Screen ");
        add(jLabel9);
        jLabel9.setBounds(590, 10, 190, 28);
    }//GEN-END:initComponents


    private void insertLocationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertLocationBtnActionPerformed
    clearData();
    Location_idUpdate = 0;
    define_location.setVisible(true);  
    }//GEN-LAST:event_insertLocationBtnActionPerformed


    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
    try {
        define_location.setVisible(false);
        if (jTextField1.getText()!= null){
        setTableModel(Locationbusiness.searchLocation(jTextField1.getText()));
        jTextField1.setText(null);}
        else 
        setTableModel(Locationbusiness.ListAll()); 
        
    } 
    catch(java.lang.NullPointerException e){
        JOptionPane.showMessageDialog(this, "This location isn't existed ");    
    }
    catch (Exception e) {
        // TODO: Add catch code
        e.printStackTrace();
    }  
    
    }//GEN-LAST:event_searchActionPerformed

    private void deleteLocationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLocationBtnActionPerformed
    if (LocationTable.getSelectedRow() >= 0) {
          try{ 
               define_location.setVisible(false);
              String LocationIndex = LocationTable.getValueAt(LocationTable.getSelectedRow(), 0).toString();
               LocationDto selected_Location = new LocationDto(); // selected Location, To delete.
               selected_Location.setCode(LocationIndex); 
               if (Locationbusiness.deleteLocation(selected_Location)) {  //if returned true, location will be deleted
                      JOptionPane.showMessageDialog(this, "Location is Deleted Successfully");
                      setTableModel(Locationbusiness.ListAll()); 
                      LocationTable.repaint() ; }
              else
              JOptionPane.showMessageDialog(this, "Can't delete this Location ! ");         
             } 
         catch(Exception e){
            e.printStackTrace();
            }
    }
    else { // if no location is selected on the table
            JOptionPane.showMessageDialog(this, "you should select a location to delete  ");
        }
    }//GEN-LAST:event_deleteLocationBtnActionPerformed

    private void updateLocationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateLocationBtnActionPerformed
     if (LocationTable.getSelectedRow()>=0) {
         // No need to update Id, so we hide it//
            
           try{
             code.setText(LocationTable.getValueAt(LocationTable.getSelectedRow(), 0).toString());
             desc.setText(LocationTable.getValueAt(LocationTable.getSelectedRow(), 1).toString());
             capacity.setText(LocationTable.getValueAt(LocationTable.getSelectedRow(), 2).toString());
             define_location.setVisible(true);
               // flag , if it equals 1 we update, if zero we insert  
             Location_idUpdate = 1; 
               code.setEnabled(false);
           }catch(Exception e){
               e.printStackTrace();
      }
     }
   else JOptionPane.showMessageDialog(this, " you should select a location to update ");
   
    }//GEN-LAST:event_updateLocationBtnActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
     try{ 
            //Create Dto Objects to get data from UI and then pass it to Bao//
            BuildingDto BuildingObject = new BuildingDto();
            FloorDto FloorObject = new FloorDto();
            LocationTypeDto LocationTypeObject = new LocationTypeDto();
            LocationDto LocationObject = new LocationDto();
          
            //To get data from UI//
            LocationObject.setCode(code.getText());
            LocationObject.setCapacity(Integer.parseInt(capacity.getText()));
            LocationObject.setDescription(desc.getText());
          
          //  LocationObject.setLocation_equipments(EquipmentList.getSelectedValuesList());
           
           
             //To set id for building ,floor , locationType//
            BuildingObject.setBuilding_id(Allbuildings.get(building_combo.getSelectedIndex()).getBuilding_id());
            FloorObject.setBuilding(BuildingObject);
            FloorObject.setFloor_id(Allfloors.get(floor_combo.getSelectedIndex()).getFloor_id());
            LocationObject.setFloor(FloorObject);
            LocationTypeObject.setLocationType_id(AlllocationTypes.get(type_combo.getSelectedIndex()).getLocationType_id());
            System.out.println(AlllocationTypes.get(type_combo.getSelectedIndex()));
            LocationObject.setType(LocationTypeObject);
         
             //To Check whether to insert or update data// 
            if(Location_idUpdate!=0)
            {     
                    LocationObject.setUpdatedBy(LoginEngine.currentUser);
                    LocationObject.setUpdate_Date(new Date(System.currentTimeMillis()));
                if(Locationbusiness.updateLocation(LocationObject)) {//&&Equipmentbuisness.saveEquipment(SelectedEquipments, LocationObject)
                    JOptionPane.showMessageDialog(this, "Location Updated Successfully");
                    setTableModel(Locationbusiness.ListAll());
                      }
                else
                JOptionPane.showMessageDialog(this, "Error occured in update");}
            
            else
            {    
            LocationObject.setInsertedBy(LoginEngine.currentUser);
            LocationObject.setInertion_Date(new Date(System.currentTimeMillis()));
                if( Locationbusiness.insertLocation(LocationObject)){
                JOptionPane.showMessageDialog(this, "Location Saved Successfully");
                setTableModel(Locationbusiness.ListAll());
                code.setEnabled(true);
            }else
            JOptionPane.showMessageDialog(this, "Error occured in insertion");
        }

        } catch(java.lang.NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Error occured, There is an Error in data Type Or Some Of Data is Missed !");
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_saveActionPerformed

    private void building_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_building_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_building_comboActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable LocationTable;
    private javax.swing.JComboBox building_combo;
    private javax.swing.JTextField capacity;
    private javax.swing.JTextField code;
    private javax.swing.JPanel define_location;
    private javax.swing.JButton deleteLocationBtn;
    private javax.swing.JTextField desc;
    private javax.swing.JComboBox floor_combo;
    private javax.swing.JButton insertLocationBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel master;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JComboBox type_combo;
    private javax.swing.JButton updateLocationBtn;
    // End of variables declaration//GEN-END:variables
    
    // this method just to clear text and reset the valus on the insert panel
    void clearData() { // clear prvious data
        code.setText(null);
        desc.setText(null);
        capacity.setText(null);
        
    }
    
    
   
}
